stages:
  - test

sonarqube-check:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli
    entrypoint: [""]
  variables:
    SONAR_HOST_URL: "http://localhost:9000"  
    SONAR_TOKEN:               
  script:
    - sonar-scanner
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
